version: "3"

networks:
  golang:

services:

  db:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=go_app
    networks:
      - golang

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    command: go run ./cmd/golang-app-server
    volumes:
      - .:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - golang
