swagger: "2.0"
info:
  description: My first Go application
  title: My Go App
  version: 1.0.0
consumes:
  - application/json
produces:
- application/json
schemes:
- http
paths:
  /users:
    get:
      tags:
        - users
      responses:
        200:
          description: list all users
          schema:
            type: array
            items:
              $ref: "#/definitions/user"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
definitions:
  user:
    type: object
    required:
      - email
      - password
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      email:
        type: string
        minLength: 1
        maxLength: 255
      password:
        type: string
        minLength: 1
        maxLength: 255
      name:
        type: string
        minLength: 1
        maxLength: 255
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
